import type { ItemType, NoteItem } from '../types/note'
import type { User } from '../types/user'

const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'

/**
 * HTTP error carrying the response status. Network failures surface as
 * TypeError (fetch itself throwing), so callers can distinguish "the server
 * answered 401/403" from "the request never reached the server" — required
 * for the offline auth snapshot: a network failure must never log a cached
 * user out (App.tsx). Messages are identical to the previous plain Error.
 */
export class ApiError extends Error {
  readonly status: number
  /**
   * Response headers — gives the sync engine access to Retry-After (Phase 4)
   * without coupling the generic API client to sync-specific logic.
   */
  readonly headers: Readonly<Record<string, string>>

  constructor(message: string, status: number, headers?: Record<string, string>) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.headers = headers ?? {}
  }
}

async function request<T>(
  path: string,
  options: RequestInit = {},
  okStatuses: readonly number[] = [],
): Promise<T> {
  const response = await fetch(`${BASE_URL}${path}`, {
    ...options,
    credentials: 'include',
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

  // Some endpoints treat specific non-2xx statuses as acceptable outcomes
  // (e.g. DELETE returns 404 when the item is already gone).
  if (okStatuses.includes(response.status)) {
    return (await response.json()) as T
  }

  if (!response.ok) {
    let message = `Request failed (${response.status})`
    try {
      const data = (await response.json()) as { error?: string }
      if (data.error) message = data.error
    } catch {
      // Keep the HTTP status message when the response is not JSON.
    }
    // Collect lowercased response headers so callers can read Retry-After,
    // Content-Type, etc. without a second response parse.
    const hdrs: Record<string, string> = {}
    response.headers.forEach((v, k) => {
      hdrs[k.toLowerCase()] = v
    })
    throw new ApiError(message, response.status, hdrs)
  }

  return (await response.json()) as T
}

export function getItems(): Promise<NoteItem[]> {
  return request<NoteItem[]>(`/items?_t=${Date.now()}`, { cache: 'no-store' })
}

export function createItem(data: {
  title: string
  content: string
  type: ItemType
  /** Optional idempotency key (offline-first Phase 2). Generated by the
   * future sync/store layer — never here — and stable across retries of the
   * same CREATE. Omitted for all current online callers. */
  clientRequestId?: string
}): Promise<NoteItem> {
  return request<NoteItem>('/items', {
    method: 'POST',
    body: JSON.stringify(data),
  })
}

export function updateItem(
  id: string,
  data: {
    title?: string
    content?: string
    type?: ItemType
    completed?: boolean
  },
): Promise<NoteItem> {
  return request<NoteItem>(`/items/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(data),
  })
}

export function deleteItem(id: string): Promise<void> {
  // Soft-delete: the item moves to Deleted, not permanently removed.
  // A 404 means it was already deleted — same final state.
  return request<void>(`/items/${id}`, { method: 'DELETE' }, [404])
}

export function getDeletedItems(): Promise<NoteItem[]> {
  return request<NoteItem[]>('/items/deleted')
}

export function restoreItem(id: string): Promise<NoteItem> {
  return request<NoteItem>(`/items/${id}/restore`, { method: 'PATCH' })
}

export function permanentDeleteItem(id: string): Promise<void> {
  return request<void>(`/items/${id}/permanent`, { method: 'DELETE' }, [404])
}

// Auth functions
export function getCurrentUser(): Promise<User> {
  return request<User>('/auth/me')
}

export function updateProfile(name: string): Promise<User> {
  return request<User>('/auth/me', {
    method: 'PATCH',
    body: JSON.stringify({ name }),
  })
}

export function logout(): Promise<void> {
  return request<void>('/auth/logout', { method: 'POST' })
}

export function getGoogleAuthUrl(): string {
  return `${BASE_URL}/auth/google`
}
